### ISSUE TITLE
Disconnect

### ISSUE THREAD

**Issue by D1ag0nall3y** [mmende/homebridge-samsungtv-control#1]
When telling SIRI, Turn TV off(this is my only test), home bridge outputs.
Samsung Remote Client: disconnected from 10.0.1.5:55000

The TV never turns off. What is the expected behavior and do I have to programmatically define each phrase to correspond with the "Remote Keys"?

**Comment by mmende** [comment]
When this message was logged the poweroff key was send to the tv (with ip 10.0.1.5). You should check that your tv allows controlling it over network (somewhere in the tv settings). Furthermore there might also pop up a message asking you if you want to allow this plugin control your tv.

**Comment by Astroman** [comment]
I just installed this plugin and am having the same problem. I know network control is enabled since I am able to use various apps on my iOS devices and I get a notification when they connect for the first time. For this plugin, I get no notification on the TV.

**Comment by neilpatel121** [comment]
i have the same issue with the disconnect, also have a newer samsung model that runs on the tizen os.. any update on getting this plugin working on the new versions of samsung tvs?

**Comment by mmende** [comment]
The new remote control api seems to work over websockets and some upnp. Unfortunately it seems like nobody managed to publish a working implementation for tizen tv's remote control api yet and in my researches about this topic I could not find any official api docs from samsung. As long as this wont change this plugin will unfortunately be restricted to samsung tv's with the old network protocol.

**Comment by mmende** [comment]
### Update:

I played around with upnp with tizen and non tizen tv's and found methods to control the volume and a sendKeyCode function that looks like a other way to send keycodes such as the current plugin does. The old non-tizen tv let me control volume, brightness etc. over this functions without any authentication but the tizen tv only allows getting those values without authenticating. To change the channel I can hopefully use the upnp sendKeyCode function but I didn't figure out how to use it correctly since it requires a keyCode number and a keyDescription string (as for the volume etc. functions the sendKeyCode function did not work on the tizen tv without authentication here). I hope that the tizen tv allows controlling it over these api's after authenticating it and keep you up to date.

**Comment by neilpatel121** [comment]
I assume it must be possible since I use simple control and they are able
to chance channels.. Maybe I can use q packet sniffer on the network to see
what commands they are sending.. will keep you posted if I find anything

**Comment by mmende** [comment]
Someone posted a working version of a command line tool for windows that pairs with the newer tv's and is able to send some keycodes to tizen tv's (at least it worked for me). You can find the link [here](https://community.smartthings.com/t/samsung-smart-tv-support/741/69#post_69). It seems like he used the smartview dll's from samsung to get this to work so it's unfortunately not directly visible how the pairing is implemented there. However I sniffed the communication when the tool is pairing to my tv and when it just sends a command after being paired already and the pattern is the following:

For pairing:
1. GET `http://<ip>:8080/ws/apps/CloudPINPage`
2. GET `http://<ip>:8080/ws/pairing?step=0&app_id=<some_app_id>&device_id=<some_device_id>&type=1` ...this triggers the pin screen on the tv
3. POST `http://<ip>:8080/ws/pairing?step=1&app_id=<some_app_id>&device_id=<some_device_id>` with `{"auth_Data": {"auth_type": "SPC", "GeneratorServerHello": <pin_something_hash>}}` where `<pin_something_hash>` has a composition as described [here](https://github.com/aclytle/samsung_tv_ip_remote/issues/1#issuecomment-146362386)
4. POST `http://<ip>:8080/ws/pairing?step=2&app_id=<some_app_id>&device_id=<some_device_id>` with `{"auth_Data": {"auth_type": "SPC", "request_id": <some_number>, "ServerAckMsg": <some_ack_msg>}}`
5. DELETE `http://<ip>:8080/ws/apps/CloudPINPage/run`

Afterwards a GET request ist made to `http://<ip>:8000/socket.io/1/?t=<timestamp>` to receive a websocket connection url like `http://<ip>:8000/socket.io/1/websocket/1AQhMAUMI-mJNiAFpADu?t=<timestamp>`. (When I try to get a websocket connection like that without pairing the tv socket just hangs up...)

When the TV is paired then, to send a command only step 1 is made before the websocket connection will be established as described. The problem now is that I have no idea how the hash is composed.

**Comment by jonferreira** [comment]
Hey,
I'm also trying to reverse-engineer the above cmd  but it's proving to be a challenge! I'd really want to use it with node-red...
Oh why did I bought a J series TV!? :(

On a side note you should be able to use UPnP to do some basic control, these are the Available actions on a JU7500

EnforceAKE
GetAvailableActions
GetBannerInformation
GetChannelListURL
GetCurrentExternalSource
GetCurrentMainTVChannel
GetDTVInformation
GetDetailProgramInformation
GetMBRDeviceList
GetRecordChannel
GetSourceList
SendMBRIRKey
SetAntennaMode
SetMainTVChannel
SetMainTVSource
StartCloneView
StartExtSourceView
StartSecondTVView
StopRecord
StopView

**Comment by Alblahm** [comment]
I have a Samsung UE32J6300, and it is connected to my Wifi network, in fact if I use a Browser and navigate to the TV address I get a response with all the TV info.
http://192.168.1.8:8001/api/v2/

> {
>   "id": "uuid:cd8319ca-5e83-42c4-a840-1a674c9d4a86",
>   "name": "[TV] Samsung",
>   "version": "2.0.24",
>   "device": {
>     "type": "Samsung SmartTV",
> ...
> }

but I've tried to use this homebridge plugin but I always get the same response:

>   [Tue Nov 15 2016 20:20:15 GMT+0100 (CET)] Loaded plugin: homebridge-samsungtv-control
>   [Tue Nov 15 2016 20:20:15 GMT+0100 (CET)] Registering accessory 'homebridge-  samsungtv.SamsungTV'
>   [Tue Nov 15 2016 20:20:15 GMT+0100 (CET)] ---
>   [Tue Nov 15 2016 20:20:15 GMT+0100 (CET)] Loaded config.json with 1 accessories and 0 platforms.
>   [Tue Nov 15 2016 20:20:15 GMT+0100 (CET)] ---
>   [Tue Nov 15 2016 20:20:15 GMT+0100 (CET)] Loading 1 accessories...
>   [Tue Nov 15 2016 20:20:15 GMT+0100 (CET)] [Bedroom TV] Initializing SamsungTV accessory...

if I try to change the vol, or turn on, or any option inside the elgato app, I see this in the log screen on the remote session.

>   [Tue Nov 15 2016 20:39:43 GMT+0100 (CET)] [Bedroom TV] Could not send volume key KEY_VOLUP:   Samsung Remote Client: Device is off or unreachable
>   Samsung Remote Client: disconnected from 192.168.1.8:55000

Any idea ??? Can I do any test to help on this driver improvement ?

**Comment by jonferreira** [comment]
well it's a J series so doubt it will ever work

**Comment by SzilagyiR** [comment]
Hi!

It is work with UE48H6400 ?

**Comment by mmende** [comment]
It seems like this specific model was released in 2014. Therefore chances are good that this TV is running Orsay and supports the old network protocol. I guess you have to figure it out yourself by installing the plugin and check whether it works or not (remember that turning ON the TV doesn't work).

**Comment by SzilagyiR** [comment]
I tried, but it not worked. TV not turning off.

log:
`Samsung Remote Client: disconnected from 10.0.1.105:55000`

**Comment by monsieurxu** [comment]
it seems this developer has successfully retro engineered the protocol myTifi 
https://appsto.re/fr/XVWvA.i

**Comment by mmende** [comment]
Thanks for the tip, I already use this app from time to time. However I guess the developer won't provide his code or a documentation on how to accomplish what they did within the app since this would allow others to create similar apps.

**Comment by smka** [comment]
hello! i've ue46es6100. 
Could not turn TV on: Samsung Remote Client: Device is off or unreachable.
Samsung Remote Client: disconnected from 192.168.1.63:55000

Is there any way to turn on the tv? Plugin allowed - turning off works perfectly!

**Comment by caiminnl** [comment]
I've managed turning the TV on by doing it with HDMI-CEC. If your samsung tv has Anynet, it has hdmi-cec. You'll need a computer connected to your PC with a hdmi-cable. For me I'm running homebridge on a raspberry pi, which supports hdmi-cec. You could simply install a homebridge plugin for this action, but it will give you a second switch in homekit. One for switching on, one to switch the tv off. Not really the most beautiful way of implementing it, but it works.

Also, for me I'm running Kodi as well on the same raspberry pi, and this plugin broke hdmi-cec support for kodi (to navigate Kodi with your tv remote), because only one program can run the hdmi-cec program at a time.  Which was quite annoying. (But a quite specific setup situation I guess.)

After installing a plugin in Kodi calles Json-cec, I was able to let Kodi send the hdmi-cec signal for turning the tv on, which is triggered by a json-url. (Big plus, now the homebridge pc doesn't need to be connected to the tv, only a device running Kodi.) After implementing this url in the samsungtv-control script where it tries to turn the tv on, it does turn the tv on, with the same switch used to turn the tv off. But a script for a http-switch will work if you're running kodi at multiple devices with different tv's.

Only downsides I'm aware off are 1. there is a delay in turning the tv on, but just a second 2. it starts the tv at the channel of the Kodi device. 

Something like this needs to be done if you want to turn the samsung tv on, if this script doesn't do the trick itself. If it doesn't turn on with this script, your tv loses network connection after turning the tv off.

**Comment by nspinelli** [comment]
@mmende  - what are you using as your <app_id>? Have you created an application in their IDE and using what was generated there? Did you use the <app_id> from a cloud application? Did you just make up an app_id and you were able to get a pin code to generate from your TV? I am testing on a J6900.

**Comment by nspinelli** [comment]
@mmende could you share your code for how you are pairing?

**Comment by mmende** [comment]
I used random numbers or strings as app_id however when I tried to get to the point where the pin code screen would appear recently it wouldn't work any more (maybe the tv updated it's firmware). I am testing on a J6350 by the way. For testing I used [Postman](https://www.getpostman.com) to send the http requests. I recently discovered that [this library](https://github.com/Ape/samsungctl) allegedly is able to control tizen tv's as well via websockets however it didn't work for mine. If you make any progress let me know.
Kind regards

**Comment by nspinelli** [comment]
@mmende that library doesn't work on my TV either. Have you tried using uPnP with sendKeyCode? I noticed you mentioned something about it in a post on sammygo and was wondering if you were able to get that to work?

**Comment by riemers** [comment]
@mmende the samsungctl does support some newer types that only use websockets, but models H & J for instance do not follow that same path. See https://github.com/Ape/samsungctl/issues/22#issuecomment-344092608 for more information. People like myTifi use a server side based call with a .dll file that comes from https://github.com/timelery/Samsung-RemoteControl (he decrypted one of the apps) just mentioning the issue for linkage & perhaps joined effort.

**Comment by kdschlosser** [comment]
H an J models are now supported in my fork of samsungctl. I have also expand the 2016+ models capabilities as well as added support the latest websocket SSL connection on port 8002. so the library now works on 2008 to current models.  I am just finishing up adding support for the UPNP functions. I forgot to mention. those of you that have the voice recognition on the TV. samsungctl supports it. 

https://github.com/kdschlosser/samsungctl

**Comment by mmende** [comment]
The plugin has been reimplemented completely and can be found [here](https://github.com/mmende/homebridge-samsungtv-control2) now. I am closing all issues in this repository therefore. Please consider testing the new plugin and help me improve it.
