### ISSUE TITLE
Cant find my TV

### ISSUE THREAD

**Issue by John88a** [mmende/homebridge-samsungtv-control#15]
Hi, My samsung TV model is UA46D6600WJXZK, is it unsupported, or am i doing something wrong?

I followed the instructions to install the Plugin, i edited config.json, put the correct IP address, and when starting homebridge it says initialising samsung tv accessory, but after a while it continues to initialise my Hue lights, and in the home app when trying to add a accessory, nothing show up ...

Thanks

**Comment by mmende** [comment]
The plugin has been reimplemented completely and can be found [here](https://github.com/mmende/homebridge-samsungtv-control2) now. I am closing all issues in this repository therefore. Please consider testing the new plugin and help me improve it.
