### ISSUE TITLE
Помогите

### ISSUE THREAD

**Issue by yshinig** [mmende/homebridge-samsungtv-control#17]
Не могу настроить увлечение звука на F серии, где это можно сделать. Выключение работает.

**Comment by yshinig** [comment]
I can not adjust the fadness on the F series, where can I do this? Shutdown is working.

**Comment by langovoi** [comment]
Можешь попробовать мой плагин, должен работать:  https://github.com/langovoi/homebridge-upnp#readme

**Comment by mmende** [comment]
The plugin has been reimplemented completely and can be found [here](https://github.com/mmende/homebridge-samsungtv-control2) now. I am closing all issues in this repository therefore. Please consider testing the new plugin and help me improve it.
