### ISSUE TITLE
Warning: Attempt to call disposable callback twice.

### ISSUE THREAD

**Issue by roe1974** [mmende/homebridge-samsungtv-control#18]
I still get a 

Warning: Attempt to call disposable callback twice.

... is there any solution ?

Richard

**Comment by mmende** [comment]
The plugin has been reimplemented completely and can be found [here](https://github.com/mmende/homebridge-samsungtv-control2) now. I am closing all issues in this repository therefore. Please consider testing the new plugin and help me improve it.
