### ISSUE TITLE
Volume and channel control

### ISSUE THREAD

**Issue by fiddypal** [mmende/homebridge-samsungtv-control#7]
How do you change volume and chancel? Right now it's showing up as an on/off switch in my home app and all I can do is shut it off.

Thanks!

**Comment by mmende** [comment]
The iOS 10 home app does not support custom characteristics as the channel or volume characteristics in this plugin. To access those properties and create scenes for them you can e.g. install the HomeKit catalog app (https://developer.apple.com/library/content/samplecode/HomeKitCatalog/Listings/HMCatalog_TabBarController_swift.html) that displays those characteristics as well. After you set up scenes in this app you can also use them in the iOS 10 home app afterwards

**Comment by fiddypal** [comment]
thanks for the info!
