### ISSUE TITLE
How can i change channel or increment volume?

### ISSUE THREAD

**Issue by osvaldoasn** [mmende/homebridge-samsungtv-control#8]
Hi, my Samsung TV turns off when i ask Siri but it can't change the channel or volume.
It appears like a switch in Home app.

Thanks!

**Comment by mmende** [comment]
Hi, the iOS Home app does not support these characteristics itself (as described here #7). You can e.g. use the [Homekit Catalog Sample App](https://developer.apple.com/library/content/samplecode/HomeKitCatalog/Introduction/Intro.html) to set up scenes for them and then use these scenes in the actual home app as well.
Hope this helps you.
