### ISSUE TITLE
What type of device / accessory I must select in homekit?

### ISSUE THREAD

**Issue by hdmvide** [mmende/homebridge-samsungtv-control#9]
After starting Homebridge, I open the home app in iOS for add a new accessory. I select Homebridge and insert the code to finish pairing.

Select "TV Living room" as Homebridge accessory and select "switch" as a type.

At this point the only operation that can play with the TV is to turn it off, because the accessory is a only switch. I did not understand how I can perform other operations such as volume, channels etc ...

can you help me?
Thanks

**Comment by mmende** [comment]
Hi,
The iOS 10 home app is currently not capable of changing custom characteristics as volume an channel are. To change those properties you can however use a sample app from Apple called [HomeKit catalog](https://developer.apple.com/library/content/samplecode/HomeKitCatalog/Introduction/Intro.html) that also displays those properties and allows creating scenes for them. These scenes are also visible in the iOS 10 home app afterwards and can be triggered as usual.
Hope this helps.
Kind regards

**Comment by hdmvide** [comment]
Thank you very much

**Comment by flexyneat** [comment]
Hi,
I'm a bit of a newbie, and just like the original post; i also have my tv displayed as a switch in the home app, with the option to only turn off the tv - which works fine. But I don't know how to go about changing channels or adjusting volume.
Could you please help explain abit further with regard to the homekit catalog? I couldnt quite make much sense from it. It seemed like a swift code

**Comment by mmende** [comment]
Hi,
The home app unfortunately only displays [predefined characteristics](https://developer.apple.com/reference/homekit/hmcharacteristic/characteristic_types) such as power state, temperature etc. for example but apple did not yet add characteristics for the volume or channel of a device. The homekit catalog example app however displays custom characteristics and allows modify them. Also all scenes created in the homekit catalog app are also available in the home app afterwards.

The [homekit catalog](https://developer.apple.com/library/content/samplecode/HomeKitCatalog/Introduction/Intro.html) app is an example project in form of source code etc. to be build with Xcode. If you have a mac with XCode installed, to install the app onto your iPhone you:
1. connect the phone to your mac
2. open the `HMCatalog.xcodeproj` file inside the downloaded project with XCode
3. select your iPhone in the dropdown menu in the upper left corner of XCode and
4. hit the build button (▶) to build the app on your device

Hope this helps...

**Comment by flexyneat** [comment]
Thanks so much. Worked like a charm.

**Comment by jat80** [comment]
@mmende so just to clarify once this is installed no modification needs to be done to the example config file?  Could I technically just say "siri turn up the volume" etc without the homekit catalog app?  Sorry if this is already explained but i'm just not sure how this works.

**Comment by mmende** [comment]
Hi,

There are certain specified characteristics such as the on/off state of a device or e.g. the temperature of a room. For these specified characteristics apple tried to cover all the possible expressions you could use to adjust those properties like for the on/off state: **_turn on/off device X_** or **_is X on?_** or for more complex characteristics like temperature e.g. **_increase the temperature by 2°_** or something like that.

By now the list of characteristics is pretty sparse and does not include the channel or volume of a device. As a workaround you can specify a scene or in other words a specific phrase that simply adjusts specific properties in a certain way if spoken. The native home app unfortunately does not display custom characteristics unlike to the homekit catalog app. Therefore to create scenes for the volume or channel you must build the homekit catalog app onto your iphone, create a scene like **_turn up the volume_** and for this scene e.g. slide the volume bar in the homekit catalog app to 2 (to increase the volume by two units).

If you TV is supported you only must change the ip_address in the config file and restart homebridge.

Kind regards

**Comment by StarlightDown** [comment]
Hello. Do you know if HomeKit Catalog is still working as of December 2017? I'm using Xcode 8.3.3 and iOS 11.2.1. Building the app onto my iPhone 6s throws up a bunch of buildtime errors, which only get worse as I try to fix them. For example, Xcode says I have to convert to a newer Swift language version, but once I change to Swift 3, the compiler suddenly gives a bunch more syntax errors. I don't know coding so I can't fix any of these. Did you have so much trouble downloading the app?

**Comment by StarlightDown** [comment]
OK, I figured out part of the problem. I was supposed to use Swift 2.3, not Swift 3. But Xcode 8 still doesn't gel well with iOS 11.

**Comment by StarlightDown** [comment]
Never mind, I figured it out. Thanks for the guides.

**Comment by mmende** [comment]
The plugin has been reimplemented completely and can be found [here](https://github.com/mmende/homebridge-samsungtv-control2) now. I am closing all issues in this repository therefore. Please consider testing the new plugin and help me improve it.
